version: '2'
services:
  testjhipsterdocuploads-app:
    image: testjhipsterdocuploads
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://testjhipsterdocuploads-mysql:3306/testjhipsterdocuploads?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://testjhipsterdocuploads-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://testjhipsterdocuploads-elasticsearch:9200
    ports:
      - 8079:8079
  testjhipsterdocuploads-mysql:
    extends:
      file: mysql.yml
      service: testjhipsterdocuploads-mysql
  testjhipsterdocuploads-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: testjhipsterdocuploads-elasticsearch
